# -*- coding: utf-8 -*-
"""Real-Time Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6-H9stxuAubkKQ7wVKKzBMsmtMQyT7L
"""

!pip install snscrape
!pip install nltk

!pip install tweepy
!pip install textblob
!pip install wordcloud
!pip install matplotlib seaborn
!pip install nltk

import tweepy
import pandas as pd
import numpy as np
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
import re
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

plt.style.use("ggplot")
nltk.download('stopwords')

import requests

BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAJYE3QEAAAAAr4DjcNVvoHduVOTW%2Fwq8A9dj8Lk%3DOaB72IOVDNMy609Rzpzk7y24g4XFOsXc9SH0rifgAkdRY2VKv6'

headers = {
    'Authorization': f'Bearer {BEARER_TOKEN}',
    'User-Agent': 'v2RecentSearchPython'
}

def get_tweets(query, max_results=100):
    search_url = "https://api.twitter.com/2/tweets/search/recent"
    query_params = {
        'query': query,
        'max_results': min(max_results, 100),
        'tweet.fields': 'created_at,lang',
    }
    response = requests.get(search_url, headers=headers, params=query_params)
    if response.status_code != 200:
        raise Exception(f"Request returned an error: {response.status_code}, {response.text}")
    return response.json()

tweets_data = get_tweets("Chelsea FC", max_results=50)


tweets = pd.DataFrame([{
    "created_at": tweet["created_at"],
    "text": tweet["text"]
} for tweet in tweets_data["data"]])

tweets.head()